---
- hosts: dev
  become: true
  tasks:
    - apt:
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes
    - raw: "echo Welcome to 28minutes | sudo tee /var/www/html/index.html" 