---
- hosts: qa
  vars: 
#    system: "Windows"
#    color: "Red"
  tasks:
#    - debug: var=hostvars
#    - debug: var=ansible_system
#    - debug: var=color
#      when: ansible_system == 'Linux'    
    - debug: var=item
      with_items:
      - item1
      - item2
    - debug: var=item
      with_items:
      - name: Range
        country: India
      - name: Jane
        country: US
      - name: Does
        country: Netherlands
